apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apirestaurant.fullname" . }}-config
data:
  DATABASE_URL: {{ include "apirestaurant.databaseUrl" . | quote }}

  # DATABASE_URL: >-
  # postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}