apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apirestaurant.fullname" . }}-secrets
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_DB: "{{ .Values.postgres.db }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"